"""transportation domain foundation (TASK-201)

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-06

Adds the canonical transportation domain tables per
docs/architecture/PHASE2_DESIGN.md: intersections, roads, road_segments
(the persisted road-network topology - PostGIS is the system of record,
not an in-memory OSM graph), stops, routes, route_stops, service_calendars,
vehicles, vehicle_assignments.

Hand-written (not autogenerated) to keep full control over PostGIS
geometry columns and constraint naming - every constraint/index name here
is chosen to exactly match app/models/*.py's __table_args__, so a future
`alembic revision --autogenerate` diff comes up empty.
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID as PGUUID

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    ]


def upgrade() -> None:
    # --- intersections ---------------------------------------------------
    op.create_table(
        "intersections",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column(
            "location",
            geoalchemy2.Geometry(geometry_type="POINT", srid=4326, spatial_index=False),
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False, server_default="manual"),
        sa.Column("osm_node_id", sa.BigInteger(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("source IN ('osm', 'manual')", name="ck_intersections_source"),
        sa.UniqueConstraint("osm_node_id", name="uq_intersections_osm_node_id"),
    )
    op.create_index(
        "ix_intersections_location", "intersections", ["location"], postgresql_using="gist"
    )

    # --- roads -------------------------------------------------------------
    op.create_table(
        "roads",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("road_class", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False, server_default="manual"),
        *_timestamps(),
        sa.CheckConstraint("source IN ('osm', 'manual')", name="ck_roads_source"),
    )

    # --- road_segments -------------------------------------------------------
    op.create_table(
        "road_segments",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column(
            "road_id",
            PGUUID(as_uuid=True),
            sa.ForeignKey("roads.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "start_intersection_id",
            PGUUID(as_uuid=True),
            sa.ForeignKey("intersections.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "end_intersection_id",
            PGUUID(as_uuid=True),
            sa.ForeignKey("intersections.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "geometry",
            geoalchemy2.Geometry(geometry_type="LINESTRING", srid=4326, spatial_index=False),
            nullable=False,
        ),
        sa.Column("length_m", sa.Float(), nullable=True),
        sa.Column("is_oneway", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("road_class", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False, server_default="manual"),
        sa.Column("osm_way_id", sa.BigInteger(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("source IN ('osm', 'manual')", name="ck_road_segments_source"),
        sa.UniqueConstraint("osm_way_id", name="uq_road_segments_osm_way_id"),
    )
    op.create_index(
        "ix_road_segments_geometry", "road_segments", ["geometry"], postgresql_using="gist"
    )
    op.create_index("ix_road_segments_road_id", "road_segments", ["road_id"])
    op.create_index(
        "ix_road_segments_start_intersection_id", "road_segments", ["start_intersection_id"]
    )
    op.create_index(
        "ix_road_segments_end_intersection_id", "road_segments", ["end_intersection_id"]
    )

    # --- stops (extends doc 04) ----------------------------------------------
    op.create_table(
        "stops",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column("code", sa.Text(), nullable=False, unique=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.Geometry(geometry_type="POINT", srid=4326, spatial_index=False),
            nullable=False,
        ),
        sa.Column("capacity_hint", sa.Integer(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False, server_default="manual"),
        sa.Column("source_id", sa.Text(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("source IN ('osm', 'gtfs', 'manual')", name="ck_stops_source"),
        sa.UniqueConstraint("source", "source_id", name="uq_stops_source_source_id"),
    )
    op.create_index("ix_stops_location", "stops", ["location"], postgresql_using="gist")

    # --- routes (extends doc 04) ---------------------------------------------
    op.create_table(
        "routes",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column("code", sa.Text(), nullable=False, unique=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "geometry",
            geoalchemy2.Geometry(geometry_type="LINESTRING", srid=4326, spatial_index=False),
            nullable=True,
        ),
        sa.Column("direction", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False, server_default="manual"),
        sa.Column("source_id", sa.Text(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("source IN ('osm', 'gtfs', 'manual')", name="ck_routes_source"),
        sa.UniqueConstraint("source", "source_id", name="uq_routes_source_source_id"),
    )
    op.create_index("ix_routes_geometry", "routes", ["geometry"], postgresql_using="gist")

    # --- route_stops (doc 04, PK already decided as (route_id, sequence)) ----
    op.create_table(
        "route_stops",
        sa.Column(
            "route_id",
            PGUUID(as_uuid=True),
            sa.ForeignKey("routes.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("sequence", sa.Integer(), primary_key=True),
        sa.Column(
            "stop_id",
            PGUUID(as_uuid=True),
            sa.ForeignKey("stops.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("scheduled_offset_s", sa.Integer(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("sequence >= 0", name="ck_route_stops_sequence_nonnegative"),
    )
    op.create_index("ix_route_stops_stop_id", "route_stops", ["stop_id"])

    # --- service_calendars -----------------------------------------------------
    op.create_table(
        "service_calendars",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column("code", sa.Text(), nullable=False, unique=True),
        sa.Column("monday", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("tuesday", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("wednesday", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("thursday", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("friday", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("saturday", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("sunday", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        *_timestamps(),
        sa.CheckConstraint("end_date >= start_date", name="ck_service_calendars_date_range"),
    )

    # --- vehicles (extends doc 04) ---------------------------------------------
    op.create_table(
        "vehicles",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column("external_code", sa.Text(), nullable=False, unique=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False, server_default="real"),
        sa.Column("status", sa.Text(), nullable=False, server_default="active"),
        *_timestamps(),
        sa.CheckConstraint("source IN ('real', 'simulated')", name="ck_vehicles_source"),
        sa.CheckConstraint(
            "status IN ('active', 'spare', 'maintenance')", name="ck_vehicles_status"
        ),
    )

    # --- vehicle_assignments (new, Phase 2 static fleet-planning concept) ------
    op.create_table(
        "vehicle_assignments",
        sa.Column("id", PGUUID(as_uuid=True), primary_key=True),
        sa.Column(
            "vehicle_id",
            PGUUID(as_uuid=True),
            sa.ForeignKey("vehicles.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "route_id",
            PGUUID(as_uuid=True),
            sa.ForeignKey("routes.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "service_calendar_id",
            PGUUID(as_uuid=True),
            sa.ForeignKey("service_calendars.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False, server_default="active"),
        *_timestamps(),
        sa.CheckConstraint("status IN ('active', 'ended')", name="ck_vehicle_assignments_status"),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name="ck_vehicle_assignments_date_range",
        ),
        sa.UniqueConstraint(
            "vehicle_id",
            "route_id",
            "service_calendar_id",
            "valid_from",
            name="uq_vehicle_assignments_natural_key",
        ),
    )
    op.create_index("ix_vehicle_assignments_vehicle_id", "vehicle_assignments", ["vehicle_id"])
    op.create_index("ix_vehicle_assignments_route_id", "vehicle_assignments", ["route_id"])
    op.create_index(
        "ix_vehicle_assignments_service_calendar_id",
        "vehicle_assignments",
        ["service_calendar_id"],
    )


def downgrade() -> None:
    op.drop_table("vehicle_assignments")
    op.drop_table("vehicles")
    op.drop_table("service_calendars")
    op.drop_table("route_stops")
    op.drop_table("routes")
    op.drop_table("stops")
    op.drop_table("road_segments")
    op.drop_table("roads")
    op.drop_table("intersections")
